// <auto-generated />
using System;
using Bag_and_Shop_app.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bag_and_Shop_app.Migrations
{
    [DbContext(typeof(BagAndShopDBContext))]
    [Migration("20260305025526_campos_novos_da_campanha")]
    partial class campos_novos_da_campanha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bag_and_Shop_app.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attribute_definition")
                        .HasColumnType("int");

                    b.Property<string>("Campaign_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enable_multiclasses")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_store_open")
                        .HasColumnType("bit");

                    b.Property<int>("MasterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Players_limit")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.HasIndex("StoreId");

                    b.HasIndex("SystemId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Bag_and_Shop_app.Domain.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("Bag_and_Shop_app.Domain.Entities.SystemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("System_code")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemEntities");
                });

            modelBuilder.Entity("Bag_and_Shop_app.Domain.Entities.SystemFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Default_value")
                        .HasColumnType("int");

                    b.Property<string>("Field_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Field_type")
                        .HasColumnType("int");

                    b.Property<int>("Field_value")
                        .HasColumnType("int");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("systemFields");
                });

            modelBuilder.Entity("Bag_and_Shop_app.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bag_and_Shop_app.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("Bag_and_Shop_app.Domain.Entities.User", "Master")
                        .WithMany("MasteredCampaigns")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bag_and_Shop_app.Domain.Entities.Store", null)
                        .WithMany("MasteredCampaigns")
                        .HasForeignKey("StoreId");

                    b.HasOne("Bag_and_Shop_app.Domain.Entities.SystemEntity", "System")
                        .WithMany("Campaigns")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");

                    b.Navigation("System");
                });

            modelBuilder.Entity("Bag_and_Shop_app.Domain.Entities.Store", b =>
                {
                    b.HasOne("Bag_and_Shop_app.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Bag_and_Shop_app.Domain.Entities.SystemFields", b =>
                {
                    b.HasOne("Bag_and_Shop_app.Domain.Entities.SystemEntity", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("Bag_and_Shop_app.Domain.Entities.Store", b =>
                {
                    b.Navigation("MasteredCampaigns");
                });

            modelBuilder.Entity("Bag_and_Shop_app.Domain.Entities.SystemEntity", b =>
                {
                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("Bag_and_Shop_app.Domain.Entities.User", b =>
                {
                    b.Navigation("MasteredCampaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
